import type { FieldDef } from './resources';

export interface MediaValue {
  url: string;
  alt: string;
  caption: string;
}

export type FormValue = string | boolean | MediaValue | MediaValue[] | Record<string, string>[] | null;
export type FormState = Record<string, FormValue>;

const emptyMedia = (): MediaValue => ({ url: '', alt: '', caption: '' });

/** API item → editable form values (lists become one-per-line text, numbers become strings). */
export function toFormState(fields: FieldDef[], item: Record<string, unknown> | null): FormState {
  const state: FormState = {};
  for (const field of fields) {
    const value = item?.[field.name];
    switch (field.type) {
      case 'checkbox':
        state[field.name] = Boolean(value);
        break;
      case 'number':
        state[field.name] = value === null || value === undefined ? '' : String(value);
        break;
      case 'list':
        state[field.name] = Array.isArray(value) ? value.join('\n') : '';
        break;
      case 'pairs':
        state[field.name] = Array.isArray(value) ? (value as Record<string, string>[]).map((row) => ({ ...row })) : [];
        break;
      case 'media':
        state[field.name] = value && typeof value === 'object' ? { ...emptyMedia(), ...(value as MediaValue) } : null;
        break;
      case 'mediaList':
        state[field.name] = Array.isArray(value) ? (value as MediaValue[]).map((media) => ({ ...emptyMedia(), ...media })) : [];
        break;
      case 'select':
        state[field.name] = typeof value === 'string' ? value : field.name === 'status' ? 'draft' : '';
        break;
      default:
        state[field.name] = typeof value === 'string' ? value : '';
    }
  }
  return state;
}

/**
 * Form values → request body containing only the editable fields (the API rejects unknown keys).
 * Empty optional values are sent as empty strings / empty arrays so they can be cleared.
 */
export function toPayload(fields: FieldDef[], state: FormState, mode: 'create' | 'update'): Record<string, unknown> {
  const body: Record<string, unknown> = {};
  for (const field of fields) {
    const value = state[field.name];
    switch (field.type) {
      case 'checkbox':
        body[field.name] = Boolean(value);
        break;
      case 'number': {
        const text = String(value ?? '').trim();
        if (text === '') {
          if (field.nullable) body[field.name] = null;
        } else {
          body[field.name] = Number(text);
        }
        break;
      }
      case 'list':
        body[field.name] = String(value ?? '')
          .split('\n')
          .map((line) => line.replace(/^\s*[-•*]\s*/, '').trim())
          .filter(Boolean);
        break;
      case 'pairs': {
        const [a, b] = field.keys;
        const extra = field.select?.key;
        body[field.name] = ((value as Record<string, string>[]) ?? [])
          .map((row) => ({
            [a]: (row[a] ?? '').trim(),
            [b]: (row[b] ?? '').trim(),
            ...(extra ? { [extra]: row[extra] ?? '' } : {}),
          }))
          .filter((row) => row[a] && row[b]);
        break;
      }
      case 'media': {
        const media = value as MediaValue | null;
        body[field.name] = media?.url ? { url: media.url.trim(), alt: media.alt.trim(), caption: media.caption.trim() } : null;
        break;
      }
      case 'mediaList':
        body[field.name] = ((value as MediaValue[]) ?? [])
          .filter((media) => media.url.trim())
          .map((media) => ({ url: media.url.trim(), alt: media.alt.trim(), caption: media.caption.trim() }));
        break;
      default: {
        const text = String(value ?? '').trim();
        // Slug is generated by the server when omitted on create.
        if (field.name === 'slug' && !text) break;
        if (field.type === 'select' && !text && mode === 'update') break;
        body[field.name] = text;
      }
    }
  }
  return body;
}
